### PR TITLE
Update some details on smplayer.spec

### PR DESCRIPTION
**Pull request by sergiomb2**

### CODE REVIEW

**Comment by smplayer-dev** [comment]
What does `kf5_kinit_requires` mean?

**Comment by sergiomb2** [comment]
Requires: kf5-kinit(x86-64)

you can check with `rpm -E %{?kf5_kinit_requires}`

**Comment by smplayer-dev** [comment]
> 
> Package: kf5-kinit
> summary: KDE 5 process launcher
> 
> description: kdeinit is a process launcher somewhat similar to the famous init used for booting UNIX. It launches processes by forking and then loading a dynamic library which should contain a 'kdemain(...)' function.
> 

SMPlayer doesn't have a `kdemain` function, so I don't know if this is necessary.

**Comment by sergiomb2** [comment]
OK I think, I just replaced, `%{?_qt4_version:Requires: qt4%{?_isa} >= %{_qt4_version}}` by `%{?kf5_kinit_requires}` , but after checking , indeed,  is not necessary .
Commit updated

**Comment by sergiomb2** [comment]
BTW another question, the URL of the project  ( URL:            http://smplayer.sourceforge.net/ ) ? unfortunately  https://smplayer.sourceforge.net/ doesn't have a trusted certificate so maybe the best URL would be https://www.smplayer.info/ ?

**Comment by smplayer-dev** [comment]
> BTW another question, the URL of the project ( URL: http://smplayer.sourceforge.net/ ) ? unfortunately https://smplayer.sourceforge.net/ doesn't have a trusted certificate so maybe the best URL would be https://www.smplayer.info/ ?

Fixed.

**Comment by sergiomb2** [comment]
https://smplayer.info/images/screenshots/smplayer_skin_modern3.png redirects to  https://www.smplayer.info/images/screenshots/smplayer_skin_modern3.png

I think the best is that https://www.smplayer.info/ redirects to https://smplayer.info/ and not the other way around .

**Comment by h1z1** [comment]
> > BTW another question, the URL of the project ( URL: http://smplayer.sourceforge.net/ ) ? unfortunately https://smplayer.sourceforge.net/ doesn't have a trusted certificate so maybe the best URL would be https://www.smplayer.info/ ?
> 
> Fixed.

Can you clarify what fixed means?  Spec file still points to sourceforge whom have long since bastardized their urls.  AFAIK there is no way to link directly to a release.   Possibly related and why I checked is the released RPM cannot be audited for some reason, it completely fails with rpm2cpio, something I've never seen before.

**Comment by sergiomb2** [comment]
I think it was this commit https://github.com/smplayer-dev/smplayer/commit/7d61dc3a0e438eb193c108d5d9c5dbe14830bfe2

**Pull request closed without merging**
